version: "3.8"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.73.0
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "6831:6831/udp" # Jaeger agent UDP
      - "5778:5778" # Configuration
      - "14268:14268" # Collector HTTP
      # - "9411:9411" # Zipkin compatible
      - "4318:4318" # OTLP HTTP
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    volumes:
      - jaeger_data:/badger

  nginx-jaeger:
    image: nginx:alpine
    container_name: nginx-jaeger
    ports:
      - "8080:8080" # Expose proxy for OTLP with CORS
    volumes:
      - ./nginx-jaeger.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - jaeger

  grafana:
    image: grafana/grafana:12.2.0-17567790421
    container_name: grafana
    ports:
      - "3000:3000" # Grafana UI. Use admin / admin to access dashboard
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - jaeger

volumes:
  jaeger_data:
  grafana_data:
